### ISSUE TITLE
Doesn't work under RHEL 8.10 Gnome Version 3.32.2

### ISSUE THREAD

**Issue by sbembenek18** [ronen25/nautilus-copypath#17]
I wasn't able to get this wot work Doesn't under RHEL 8.10 Gnome Version 3.32.2

The drop down option does not appear in the menu.

**Comment by jimjoh** [comment]
I had this working in CentOS 7, but with CentOS 9 the copy path option doesn't appear.

```
cat /etc/centos-release;gnome-shell --version
CentOS Stream release 9
GNOME Shell 40.10
```

Only log I see is:
```
grep copypath /var/log/messages
Aug  9 08:54:04 myPC nautilus[3681]:  File "/home/williamgates/.local/share/nautilus-python/extensions/nautilus-copypath.py", line 16, in <module>
```

**Comment by sbembenek18** [comment]
I made some modifications and it works for me now. 
[nautilus-copypath.zip](https://github.com/user-attachments/files/16591442/nautilus-copypath.zip)

**Comment by jimjoh** [comment]
Thanks for sharing.   With your version I now have the Copy Path option, but it still doesn't work for me.  When I use Copy Path I get these errors:
```
$ Traceback (most recent call last):
  File "/home/williamgates/.local/share/nautilus-python/extensions/nautilus-copypath.py", line 138, in __copy_files_path
    paths = self.__transform_paths([
  File "/home/williamgates/.local/share/nautilus-python/extensions/nautilus-copypath.py", line 139, in <listcomp>
    fileinfo.get_location().get_path()
AttributeError: 'Box' object has no attribute 'get_location'
```
